// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, key, name, created_at, updated_at
FROM projects
WHERE id = $1 AND org_id = $2
`

type GetProjectByIDParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSingletonOrgID = `-- name: GetSingletonOrgID :one
SELECT id FROM organizations
`

func (q *Queries) GetSingletonOrgID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSingletonOrgID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, key, name, created_at, updated_at
FROM projects
WHERE org_id = $1
ORDER BY lower(key)
`

func (q *Queries) ListProjects(ctx context.Context, orgID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
