// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (family_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, family_id, user_id, token_hash, created_at, expires_at, revoked_at, replaced_by, replaced_at
`

type CreateRefreshTokenParams struct {
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.FamilyID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.ReplacedAt,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, family_id, user_id, token_hash, created_at, expires_at, revoked_at, replaced_by, replaced_at FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

// Locks the row for the rotation transaction so two concurrent refreshes of
// the same token serialize (ADR-0003).
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.ReplacedAt,
	)
	return i, err
}

const markRefreshTokenReplaced = `-- name: MarkRefreshTokenReplaced :exec
UPDATE refresh_tokens
SET replaced_by = $1, replaced_at = $2
WHERE id = $3
`

type MarkRefreshTokenReplacedParams struct {
	SuccessorID uuid.NullUUID
	ReplacedAt  pgtype.Timestamptz
	ID          uuid.UUID
}

// replaced_at is passed explicitly (not now()) so it shares the transaction's
// clock with the grace-window check in the repository.
func (q *Queries) MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenReplaced, arg.SuccessorID, arg.ReplacedAt, arg.ID)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// Revokes every not-yet-revoked token in a family in one statement; used on
// reuse detection inside the rotation transaction.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const revokeRefreshTokenFamilyByHash = `-- name: RevokeRefreshTokenFamilyByHash :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = (SELECT rt.family_id FROM refresh_tokens rt WHERE rt.token_hash = $1)
  AND revoked_at IS NULL
`

// Logout: revoke the whole family the presented token belongs to. A missing
// hash matches no family, so logout is idempotent.
func (q *Queries) RevokeRefreshTokenFamilyByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamilyByHash, tokenHash)
	return err
}
