// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title)
VALUES ($1, $2)
RETURNING id, project_id, title, status, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID uuid.UUID
	Title     string
}

type CreateTaskRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Title     string
	Status    TaskStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask, arg.ProjectID, arg.Title)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.project_id, t.title, t.status, t.created_at, t.updated_at
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE p.org_id = $1
  AND ($2::uuid IS NULL OR t.project_id = $2)
  AND ($3::task_status IS NULL OR t.status = $3)
  AND (
    $4::timestamptz IS NULL
    OR (t.created_at, t.id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $6
`

type ListTasksParams struct {
	OrgID           uuid.UUID
	ProjectID       uuid.NullUUID
	Status          NullTaskStatus
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.NullUUID
	PageSize        int32
}

type ListTasksRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Title     string
	Status    TaskStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The join is the org scope: a task is reachable only through a project in the
// caller's org, so a client-supplied project_id can narrow the result but never
// widen it (security-baseline.md).
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OrgID,
		arg.ProjectID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
