// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, org_id, project_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID    uuid.NullUUID
	OrgID      uuid.UUID
	ProjectID  uuid.NullUUID
	Action     string
	EntityType string
	EntityID   uuid.NullUUID
	Metadata   []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.OrgID,
		arg.ProjectID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}
